# Generated by Django 4.1.5 on 2023-01-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('color', models.CharField(choices=[('#0000FF', 'Blue'), ('#FF0000', 'Red'), ('#FFFF00', 'Yellow'), ('#00FF00', 'Lime'), ('#800000', 'Maroon'), ('#008000', 'Green'), ('#00FFFF', 'Aqua'), ('#000080', 'Navy'), ('#800080', 'Purple')], default='#0000FF', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.timeline')),
            ],
        ),
    ]
