# Generated by Django 4.1.5 on 2023-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_timeline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
