# Generated by Django 4.1.5 on 2023-01-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0007_alter_timeline_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
