# Generated by Django 4.1.5 on 2023-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_username'),
        ('timeline', '0009_alter_record_options_alter_record_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together={('owner', 'title')},
        ),
    ]
