# Generated by Django 4.1.5 on 2023-01-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0010_alter_timeline_title_alter_timeline_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timeline',
            unique_together=set(),
        ),
    ]
