# Generated by Django 4.1.5 on 2023-01-05 10:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, verbose_name='Task')),
                ('note', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[(1, 'Low'), (2, 'Middle'), (3, 'High')], max_length=100)),
                ('done', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='todo.tag')),
            ],
        ),
    ]
