# Generated by Django 4.1.5 on 2023-01-07 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_options_task_created_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
