# Generated by Django 4.1.5 on 2023-01-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_task_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['done', '-priority', '-created']},
        ),
    ]
